/* empty css                      */import{S as p,a as u,i as n}from"./assets/vendor-JxvvEPkb.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))o(t);new MutationObserver(t=>{for(const e of t)if(e.type==="childList")for(const a of e.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&o(a)}).observe(document,{childList:!0,subtree:!0});function i(t){const e={};return t.integrity&&(e.integrity=t.integrity),t.referrerPolicy&&(e.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?e.credentials="include":t.crossOrigin==="anonymous"?e.credentials="omit":e.credentials="same-origin",e}function o(t){if(t.ep)return;t.ep=!0;const e=i(t);fetch(t.href,e)}})();class g{constructor(s,i,o,t,e){this.searchInput=s,this.searchButton=i,this.gallery=o,this.loadingSpinner=t,this.loadMoreButton=e,this.lightbox=new p(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250}),this.queryParams={key:"45876667-2d0330e34270c14d815b5249b",q:this.searchInput.value,page:"1",image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:"40"},this.initialize()}initialize(){this.loadMoreButton.classList.add("hidden"),this.searchButton.addEventListener("click",this.handleSearch.bind(this)),this.loadMoreButton.addEventListener("click",this.loadMoreImages.bind(this))}async handleSearch(){this.queryParams.q=this.searchInput.value,this.queryParams.page=1,this.gallery.innerHTML="",await this.fetchImages()}async loadMoreImages(){this.queryParams.page++,await this.fetchImages(),this.scrollGallery()}scrollGallery(){const s=this.gallery.querySelectorAll(".gallery-item");if(s.length>1){const i=s[0].getBoundingClientRect().height;window.scrollBy({top:i*2,behavior:"smooth"})}}async fetchImages(){const s="https://pixabay.com/api/";this.loadingSpinner.classList.remove("hidden"),this.loadMoreButton.classList.remove("hidden");try{const o=(await u.get(s,{params:this.queryParams})).data,t=o.hits.map(({webformatURL:e,largeImageURL:a,tags:r,likes:c,views:d,comments:h,downloads:m})=>`
          <li class="gallery-item">
            <a href="${a}" data-lightbox="gallery" data-title="${r}">
              <img class="gallery-image" src="${e}" alt="${r}"/>
            </a>
            <div class="bottom-item">
              <div class="bottom-item-div"><p class="bottom-item-p1">Likes</p><p class="bottom-item-p2">${c}</p></div>
              <div class="bottom-item-div"><p class="bottom-item-p1">Views</p><p class="bottom-item-p2">${d}</p></div>
              <div class="bottom-item-div"><p class="bottom-item-p1">Comments</p><p class="bottom-item-p2">${h}</p></div>
              <div class="bottom-item-div"><p class="bottom-item-p1">Downloads</p><p class="bottom-item-p2">${m}</p></div>
            </div>
          </li>
        `).join("");if(this.gallery.innerHTML+=t,o.hits.length===0){n.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"red"}),this.loadingSpinner.classList.add("hidden"),this.loadMoreButton.classList.add("hidden");return}if(o.totalHits-this.queryParams.page*40<40&&this.queryParams.page>=1){this.loadMoreButton.classList.add("hidden"),this.loadingSpinner.classList.add("hidden"),n.info({title:"Info",message:"We're sorry, but you've reached the end of search results",position:"topRight",backgroundColor:"yellow"});return}this.loadMoreButton.classList.remove(),this.lightbox.refresh()}catch(i){console.error("Hata:",i)}finally{this.loadingSpinner.classList.add("hidden")}}}const y=document.getElementById("search-input"),f=document.getElementById("search-button"),b=document.getElementById("gallery"),v=document.getElementById("loading-spinner"),I=document.getElementById("load-more-button");new g(y,f,b,v,I);
//# sourceMappingURL=index.js.map
