/* empty css                      */import{S as u,a as g,i as n}from"./assets/vendor-JxvvEPkb.js";(function(){const i=document.createElement("link").relList;if(i&&i.supports&&i.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const e of t)if(e.type==="childList")for(const r of e.addedNodes)r.tagName==="LINK"&&r.rel==="modulepreload"&&s(r)}).observe(document,{childList:!0,subtree:!0});function o(t){const e={};return t.integrity&&(e.integrity=t.integrity),t.referrerPolicy&&(e.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?e.credentials="include":t.crossOrigin==="anonymous"?e.credentials="omit":e.credentials="same-origin",e}function s(t){if(t.ep)return;t.ep=!0;const e=o(t);fetch(t.href,e)}})();class p{constructor(i,o,s,t,e){this.searchInput=i,this.searchButton=o,this.gallery=s,this.loadingSpinner=t,this.loadMoreButton=e,this.currentPage=1,this.currentQuery="",this.lightbox=new u(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250}),this.initialize()}initialize(){this.loadMoreButton.classList.add("hidden"),this.searchButton.addEventListener("click",this.handleSearch.bind(this)),this.loadMoreButton.addEventListener("click",this.loadMoreImages.bind(this))}async handleSearch(){this.currentQuery=this.searchInput.value,this.currentPage=1,this.gallery.innerHTML="",await this.fetchImages()}async loadMoreImages(){this.currentPage++,await this.fetchImages(),this.scrollGallery()}scrollGallery(){const i=this.gallery.querySelectorAll(".gallery-item");if(i.length>1){const o=i[0].getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}}async fetchImages(){const i=`https://pixabay.com/api/?key=45876667-2d0330e34270c14d815b5249b&q=${this.currentQuery}&image_type=photo&orientation=horizontal&safesearch=true&page=${this.currentPage}&page_per=40`;this.loadingSpinner.classList.remove("hidden"),this.loadMoreButton.classList.remove("hidden");try{const s=(await g.get(i)).data;console.log(s);const t=s.hits.map(({webformatURL:e,largeImageURL:r,tags:a,likes:c,views:d,comments:h,downloads:m})=>`
          <li class="gallery-item">
            <a href="${r}" data-lightbox="gallery" data-title="${a}">
              <img class="gallery-image" src="${e}" alt="${a}"/>
            </a>
            <div class="bottom-item">
              <div class="bottom-item-div"><p class="bottom-item-p1">Likes</p><p class="bottom-item-p2">${c}</p></div>
              <div class="bottom-item-div"><p class="bottom-item-p1">Views</p><p class="bottom-item-p2">${d}</p></div>
              <div class="bottom-item-div"><p class="bottom-item-p1">Comments</p><p class="bottom-item-p2">${h}</p></div>
              <div class="bottom-item-div"><p class="bottom-item-p1">Downloads</p><p class="bottom-item-p2">${m}</p></div>
            </div>
          </li>
        `).join("");if(this.gallery.innerHTML+=t,s.hits.length===0){n.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"red"}),this.loadingSpinner.classList.add("hidden"),this.loadMoreButton.classList.add("hidden");return}if(console.log(s.totalHits-this.currentPage*40),s.totalHits-this.currentPage*40<40&&this.currentPage>=1){this.loadMoreButton.classList.add("hidden"),this.loadingSpinner.classList.add("hidden"),n.info({title:"Info",message:"We're sorry, but you've reached the end of search results",position:"topRight",backgroundColor:"yellow"});return}this.loadMoreButton.classList.remove(),this.lightbox.refresh()}catch(o){console.error("Hata:",o)}finally{this.loadingSpinner.classList.add("hidden")}}}const y=document.getElementById("search-input"),f=document.getElementById("search-button"),b=document.getElementById("gallery"),v=document.getElementById("loading-spinner"),L=document.getElementById("load-more-button");new p(y,f,b,v,L);
//# sourceMappingURL=index.js.map
